version: 2
updates:
  # Configuration for the oc-mirror v1 go mod (weekly security-updates)
  - package-ecosystem: "gomod"
    directory: "/v1"
    schedule:
      interval: "weekly"
    # Disable version updates, only allow security updates
    open-pull-requests-limit: 0
    groups:
      oc-mirror-v1-security-updates:
        applies-to: security-updates
        patterns: [ "*" ]

  # Configuration for the oc-mirror v2 go module (monthly version updates)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      k8s:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      openshift:
        patterns:
          - "github.com/openshift/*"
      oc-mirror-v2-version-updates:
        applies-to: version-updates
        patterns: [ "*" ]
        exclude-patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
          - "github.com/openshift/*"
      oc-mirror-v2-security-updates:
        applies-to: security-updates
        patterns: [ "*" ] 