# This config demonstrates how to mirror the minimum and maximum
# versions in the specified channel for an OpenShift release
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  ocp:
    channels:
      - name: stable-4.9
        headsOnly: false