# This example demonstrates how to mirror the latest
# okd release.
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  platform:
    channels:
      - name: okd
        type: okd