# This config uses the headsOnly feature which will mirror the 
# latest version of each channel within each package contained 
# within a specified operator catalog
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8
      headsonly: true