apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:5000/test:latest # Stores metadata in an image
    skipTLS: true # Disable TLS certificate checking or use plain HTTP 
mirror:
  ocp:
    channels:
      - name: stable-4.9 # References latest stable release
      - name: stable-4.7 # Annotation references min and max version. 
        minVersion: '4.6.13'
        maxVersion: '4.7.18'
    graph: true # Planned, include Cincinnati upgrade graph image in imageset
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8 # References entire catalog
      headsOnly: true # References latest version of each operator in catalog (true is the default value and can be omitted)
      packages:
        - name: rhacs-operator
          startingVersion: '3.67.0'
          channels:
            - name: 'latest'
  additionalimages: # List of additional images to be included in imageset
    - name: registry.redhat.io/ubi8/ubi:latest
  blockedimages: # Planned, list of base images to be blocked (best effort)
    - name: alpine
    - name: redis
  helm:
    local:
      - name: podinfo
        path: /test/podinfo-5.0.0.tar.gz
    repos:
      - name: podinfo
        url: https://stefanprodan.github.io/podinfo
        charts:
          - name: podinfo
            version: 5.0.0
