apiVersion: tmp-redhatgov.com/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:5000/test:latest # Stores metadata in an image
    skipTLS: true # Disable TLS certificate checking or use plain HTTP 
mirror:
  ocp:
    channels:
      - name: stable-4.8 # References latest stable release
      - name: stable-4.7 # Version annotation references version, does not pull latest
        versions:
          - '4.7.18'
          - '4.6.13'
    graph: true # Planned, include Cincinnati upgrade graph image in imageset
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8 # References entire catalog
      headsOnly: true # References latest version of each operator in catalog (true is the default value and can be omitted)
      packages:
        - name: couchbase-operator # Planned, overrides catalog default, respects headsOnly setting
          startingVersion: '1.4.0' # Planned, overrides catalog default, overrides headsOnly setting
        - name: crunchy-postgresql-operator
          channels: # Planned
            - name: 'stable'
  additionalimages: # List of additional images to be included in imageset
    - name: registry.redhat.io/ubi8/ubi:latest
  blockedimages: # Planned, list of base images to be blocked (best effort)
    - name: alpine
    - name: redis
  helm:
    local:
      - name: podinfo
        path: /test/podinfo-5.0.0.tar.gz
    repos:
      - name: podinfo
        url: https://stefanprodan.github.io/podinfo
        charts:
          - name: podinfo
            version: 5.0.0
